### ISSUE TITLE
Allow keywords with spaces in them

### ISSUE THREAD

**Issue by fasiha** [MarketSquare/robotframework-browser-extensions#17]
My users like the nice human-readable keyword names with spaces that are standard in Robot and would like to be able to call `My Go To Keyword` instead of `myGoToKeyword` when this is a keyword provided by `jsextension`. I thought I'd be clever and do something like:
```js
async function myGoToKeyword(pageUrl, page) {
  // ...
}
exports.__esModule = true;
exports['My Go To Keyword'] = myGoToKeyword;
```
but Robot is totally unamused:
```
[ ERROR ] Error in file '/.../my.robot' on line 5: Initializing library 'Browser' with arguments [ jsextension=/.../module.js ] failed: invalid syntax in My Go To Keyword
```

After noticing that the examples in this repo all export `PascalCase` keywords, I guess this isn't supported but thought to open this issue to track progress towards enabling this.

> If this issue belongs in another repo, please accept my apologies and feel free to close it here! 🙏

**Comment by leeuwe** [comment]
Hi! @fasiha,
This is just the way you have to code the keywords. Once you've imported the extension, it can be used as regular with spaces. So regular users shouldn't have to bother using the camelCase. For example look in the [Mendix folder](https://github.com/MarketSquare/robotframework-browser-extensions/tree/main/Mendix) of this project.
